### ISSUE TITLE
Update calendar with our events

### ISSUE THREAD

**Issue by samumantha** [coderefinery/calendar#40]

**Comment by samumantha** [comment]
Make sure that all upcoming trainings are in the calendar!

**Comment by samumantha** [comment]
Also check that all events are mentioned on the website too!

**Comment by bast** [comment]
I am taking this one since I am anyway going through the website.

**Comment by bast** [comment]
Finally updated the upcoming events on the website. There were many problems there. Now working on the calendar side.

**Comment by bast** [comment]
As far as I can see, the calendar is up-to-date. Closing.

**Comment by bast** [comment]
I broke it. Reopening.

**Comment by bast** [comment]
Not I broke it but the cross-organization calendar thing seems to have problems. Will open/comment somewhere else.
